#!/usr/bin/env python3
"""Exercise the example issuance service end to end.

Starts the service on a loopback port, requests warrants as two principals,
and checks what each warrant allows. When `--agent` names a built
`tenuo-openshell-agent`, it also installs each warrant with the agent's own
`install-warrant`, which refuses a warrant for any other holder key.

    python3 examples/issuance/test_issuer_service.py \
        --agent target/debug/tenuo-openshell-agent
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
import tempfile
import threading
import urllib.error
import urllib.request
from pathlib import Path

from tenuo import SigningKey, decode_warrant_stack_base64

sys.path.insert(0, str(Path(__file__).resolve().parent))
from issuer_service import Authenticator, Grants, Issuer, serve  # noqa: E402

HERE = Path(__file__).resolve().parent
TOKENS = {"alice": "alice-token", "bob": "bob-token"}


def post(url: str, token: str | None, body: dict) -> tuple[int, dict]:
    request = urllib.request.Request(url, data=json.dumps(body).encode(), method="POST")
    request.add_header("Content-Type", "application/json")
    if token:
        request.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(request) as response:
            return response.status, json.load(response)
    except urllib.error.HTTPError as error:
        return error.code, json.load(error)


def holder(agent: str | None, home: Path) -> tuple[str, SigningKey | None]:
    """Return a holder public key, generated by the agent when available."""
    if agent:
        env = {**os.environ, "TENUO_HOLDER_KEY_FILE": str(home / "holder.key"),
               "TENUO_WARRANT_FILE": str(home / "warrant")}
        public = subprocess.run([agent, "keygen"], env=env, check=True,
                                capture_output=True, text=True).stdout.split()[-1]
        return public, None
    key = SigningKey.generate()
    return bytes(key.public_key.to_bytes()).hex(), key


def install(agent: str, home: Path, warrant: str) -> subprocess.CompletedProcess:
    env = {**os.environ, "TENUO_HOLDER_KEY_FILE": str(home / "holder.key"),
           "TENUO_WARRANT_FILE": str(home / "warrant")}
    return subprocess.run([agent, "install-warrant", warrant], env=env,
                          capture_output=True, text=True)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--agent", help="path to a built tenuo-openshell-agent")
    args = parser.parse_args()

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        issuer_key = SigningKey.generate()
        audit = tmp / "issued.jsonl"
        issuer = Issuer(issuer_key, Grants(json.loads((HERE / "grants.json").read_text())), audit)
        callers = {hashlib.sha256(t.encode()).hexdigest(): p for p, t in TOKENS.items()}
        server = serve(issuer, Authenticator(callers), "127.0.0.1", 0)
        threading.Thread(target=server.serve_forever, daemon=True).start()
        base = f"http://127.0.0.1:{server.server_address[1]}"

        with urllib.request.urlopen(f"{base}/v1/issuer") as response:
            assert json.load(response)["public_key"] == issuer.public_key

        homes = {name: tmp / name for name in TOKENS}
        for home in homes.values():
            home.mkdir()
        holders = {name: holder(args.agent, home)[0] for name, home in homes.items()}

        issued = {}
        for name in TOKENS:
            status, body = post(f"{base}/v1/warrants", TOKENS[name],
                                {"holder": holders[name], "task": "triage", "ttl": 3600})
            assert status == 201, (name, status, body)
            issued[name] = body

        # Same task, different principals, different argument limits.
        alice = decode_warrant_stack_base64(issued["alice"]["warrant"])[-1]
        bob = decode_warrant_stack_base64(issued["bob"]["warrant"])[-1]
        for warrant, name in ((alice, "alice"), (bob, "bob")):
            assert bytes(warrant.issuer.to_bytes()).hex() == issuer.public_key
            assert bytes(warrant.authorized_holder.to_bytes()).hex() == holders[name]
            assert warrant.session_id.startswith(f"{name}/")
            assert warrant.ttl_remaining.total_seconds() <= 900, "ttl is capped at max_ttl_secs"
        assert alice.allows("read_logs", {"service": "payments", "environment": "production"})
        assert not alice.allows("read_logs", {"service": "auth", "environment": "staging"})
        assert bob.allows("read_logs", {"service": "auth", "environment": "staging"})
        assert not bob.allows("read_logs", {"service": "payments", "environment": "staging"})
        assert not bob.allows("restart_service", {"service": "auth"})

        # Refusals.
        assert post(f"{base}/v1/warrants", None, {"holder": holders["bob"], "task": "triage"})[0] == 401
        assert post(f"{base}/v1/warrants", "wrong", {"holder": holders["bob"], "task": "triage"})[0] == 401
        assert post(f"{base}/v1/warrants", TOKENS["bob"], {"holder": holders["bob"], "task": "restart"})[0] == 403
        assert post(f"{base}/v1/warrants", TOKENS["bob"], {"holder": "zz", "task": "triage"})[0] == 400
        assert post(f"{base}/v1/warrants", TOKENS["bob"],
                    {"holder": issuer.public_key, "task": "triage"})[0] == 400

        # The audit log maps every warrant id to its principal.
        records = [json.loads(line) for line in audit.read_text().splitlines()]
        assert {(r["principal"], r["warrant_id"]) for r in records} == {
            ("alice", alice.id), ("bob", bob.id)}

        if args.agent:
            for name, home in homes.items():
                result = install(args.agent, home, issued[name]["warrant"])
                assert result.returncode == 0, result.stderr
            # A warrant for one task's key does not install under another's.
            crossed = install(args.agent, homes["bob"], issued["alice"]["warrant"])
            assert crossed.returncode != 0, "install-warrant accepted another holder's warrant"

        server.shutdown()
    print("issuance example: ok" + (" (with agent install-warrant)" if args.agent else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
