FROM nvcr.io/nvidia/base/ubuntu@sha256:c280ee89f8bfcbdaba6179ad4347f60c509e841cbe63eb93002f01bf70e0819c

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates curl \
    && rm -rf /var/lib/apt/lists/* \
    && groupmod --new-name sandbox ubuntu \
    && usermod --login sandbox --home /home/sandbox --move-home ubuntu

USER sandbox
WORKDIR /home/sandbox
